### ISSUE TITLE
AOI upload checksum error

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/django-ebagis-ui#2]
The test was performed on the production site (https://ebagis.geog.pdx.edu/). The AOI (yampa_AOI_05092018) was loaded to the test site without any issue.  BAGIS-H 1.6.6-b1 was used for the upload.

![image](https://user-images.githubusercontent.com/11510708/39831977-de29da56-537a-11e8-991a-27c07bb38c25.png)

**Comment by jkeifer** [comment]
@jdduh This repo is old and not current. All the UI components for ebagis have been merged into the PSU-CSAR/django-ebagis repository, as have all other ebagis-related repos. Therefore, any ebagis issues should be opened on that PSU-CSAR/django-ebagis. To help with the confusion, I've cleaned up some old repos, and marked a couple (including this one) as archived (read-only).

Regardless, I've fixed this issue. Short answer, I had forgotten to bump the required version for one of the dependencies. I just ran a test upload to the production instance ebagis.geo.pdx.edu and it succeeded.

Longer answer, I maintain the package jkeifer/drf-chunked-upload, which is used by ebagis to implement upload support. I had patched an issue in that package, but I had postponed releasing that version until it had been tested further and had pulled the changes in manually to the test site (and then forgot I had done so). So while both the test site and the prod site showed they had the same version of this package, they were actually running different code. I released the new version to pypi and updated both instances of ebagis. I also bumped the required version in the setup script for PSU-CSAR/django-ebagis.
